r_arm_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
     - arm_joint1
     - arm_joint2
     - arm_joint3
     - arm_joint4
     - arm_joint5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      arm_joint1: {trajectory: 0.1, goal: 0.1}
      arm_joint2: {trajectory: 0.1, goal: 0.1}
      arm_joint3: {trajectory: 0.1, goal: 0.1}
      arm_joint4: {trajectory: 0.1, goal: 0.1}
      arm_joint5: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
