<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="v2mini">

<xacro:property name="pi" value="3.14159" />

<!-- base properties -->
<xacro:property name="base_offset_z" value="0.0192" />
<xacro:property name="base_collision_height" value="0.132" />
<xacro:property name="base_collision_radius" value="0.175" />

<!-- wheel properties -->
<xacro:property name="wheel_radius" value="0.03" />
<xacro:property name="wheel_offset_radial" value="0.1405" />

<!-- torso properties -->
<xacro:property name="torso_offset_z" value="0.175" />
<xacro:property name="torso_width" value="0.2373" />

<xacro:macro name="body">

  <!-- **** BASE **** -->

  <link name="base_link">
    <!-- fake inertial values -->
    <inertial>
      <mass value="10"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
      <origin/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${base_offset_z}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://v2mini_description/meshes/base/base.stl" />
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${base_collision_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_collision_height}" radius="${base_collision_radius}"/>
      </geometry>
    </collision>

  </link>

  <xacro:wheel prefix="front" reflect="-1" rotate="0" front_set="1"/>
  <xacro:wheel prefix="back" reflect="1" rotate="2" front_set="1"/>
  <xacro:wheel prefix="right" reflect="-1" rotate="-1" front_set="0"/>
  <xacro:wheel prefix="left" reflect="1" rotate="1" front_set="0"/>

  <!-- **** TORSO **** -->

  <link name="torso_link">
    <!-- fake inertial values -->
    <inertial>
      <mass value="5"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100" />
      <origin/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://v2mini_description/meshes/torso/torso.stl" />
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="torso_slide" type="prismatic">
    <parent link="base_link"/>
    <child link="torso_link"/>
    <origin xyz="0 0 ${base_offset_z}"/>
    <axis xyz="0 0 1"/>
    <limit effort="10" lower="-0.09" upper="0" velocity="0.5"/>
  </joint>

</xacro:macro>

<!-- Macro for creating base wheels -->
<xacro:macro name="wheel" params="prefix reflect rotate front_set">

  <link name="${prefix}_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${pi/2*rotate}"/>
      <geometry>
        <mesh filename="package://v2mini_description/meshes/base/base_wheel.stl" />
      </geometry>
      <material name="red"/>
    </visual>
     <inertial>
       <origin xyz="0 0 0" rpy="0 0 0"/>
       <mass value="1"/>
       <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>

  </link>

  <joint name="${prefix}_axel" type="continuous">
    <parent link="base_link"/>
    <child link="${prefix}_wheel"/>
    <origin xyz="${wheel_offset_radial*reflect*(1-front_set)} ${wheel_offset_radial*reflect*front_set} ${wheel_radius}"/>
    <axis xyz="${1-front_set} ${front_set} 0"/>
  </joint>

</xacro:macro>

</robot>
